
###
GET http://localhost:3000/comments

###
GET http://localhost:3000/comments/6752ddc21ab0d0c77af9173a

###
GET http://localhost:3000/6752ddc21ab0d0c77af9173a

###
POST  http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "6752ddc21ab0d0c77af9173a",
    "content":"This is my first comment",
    "owner":"Itai2"
}

###
PUT  http://localhost:3000/comments/6752de6f1ab0d0c77af91750
Content-Type: application/json

{
    "title": "My updated comment",
    "content": "This is my updated comment"
}

###
DELETE  http://localhost:3000/comments/6752de6f1ab0d0c77af91750
Content-Type: application/json


