
###
GET http://localhost:3000/comments

###
GET http://localhost:3000/comments/675178df1d6cb1420579443b

###
GET http://localhost:3000/comments?postId=6750b8c5ff981fbd3917a089

###
POST  http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "6750b8c5ff981fbd3917a089",
    "content":"This is my first comment",
    "owner":"Itai2"
}

###
PUT  http://localhost:3000/comments/675178df1d6cb1420579443b
Content-Type: application/json

{
    "title": "My updated comment",
    "content": "This is my updated comment"
}

###
DELETE  http://localhost:3000/comments/675178df1d6cb1420579443b
Content-Type: application/json


