### 
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "פוסט שני",
    "content": "זהו התוכן של הפוסט השני.",
    "sender": "User123",
    "ID": "315186346"
}

### קבלת כל הפוסטים
GET http://localhost:3000/posts

### קבלת פוסט לפי ID
GET http://localhost:3000/posts/6752ddc21ab0d0c77af9173a


### עדכון פוסט
PUT http://localhost:3000/posts/6752ddc21ab0d0c77af9173a
Content-Type: application/json

{
    "title": "פוסט מעודכן",
    "content": "זהו התוכן של הפוסט השני.",
    "sender": "User123"
   
}




