### 
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "פוסט שני",
    "content": "זהו התוכן של הפוסט השני.",
    "sender": "User123",
    "ID": "315186346"
}

### קבלת כל הפוסטים
GET http://localhost:3000/posts

### קבלת פוסט לפי ID
GET http://localhost:3000/posts/674dcf9740b0832bdb3a4e1a


### עדכון פוסט
PUT http://localhost:3000/posts/674dcf9740b0832bdb3a4e1a
Content-Type: application/json

{
    "title": "פוסט מעודכן",
    "content": "זהו התוכן של הפוסט השני.",
    "sender": "User123"
   
}



### הוספת תגובה
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "POST_ID_HERE",
    "content": "זוהי תגובה.",
    "commenter": "CommenterName"
}

### קבלת כל התגובות
GET http://localhost:3000/comments

### קבלת תגובות לפי פוסט
GET http://localhost:3000/comments?post=POST_ID_HERE

### עדכון תגובה
PUT http://localhost:3000/comments/COMMENT_ID_HERE
Content-Type: application/json

{
    "content": "Content"
}

### מחיקת תגובה
DELETE http://localhost:3000/comments/COMMENT_ID_HERE
